//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemoryGame.API.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rank
    {
        public int RankID { get; set; }
        public int ChallengerID { get; set; }
        public byte Best { get; set; }
        public System.DateTime DateAchieved { get; set; }
    }
}
